SEED_USER = {
    "nickname": "spotapp_gijon_seed",
    "first_name": "SpotApp",
    "last_name": "Community",
    "user_pic": None,
    "email": "gijon-seed@spotapp.local",
    "password": "seed-only-account",
}

GIJON_SPOTS = [
    {
        "spot_name": "Playa de San Lorenzo",
        "sport_type": "surfing",
        "spot_description": "Gijon's long city beach. Check the swell and local conditions before entering the water.",
        "spot_country": "Spain",
        "spot_city": "Gijon",
        "spot_street": "Paseo del Muro de San Lorenzo",
        "spot_street_number": "1",
        "latitude": 43.5436,
        "longitude": -5.6487,
    },
    {
        "spot_name": "Playa de Poniente",
        "sport_type": "surfing",
        "spot_description": "Sheltered urban shoreline west of the centre, useful for checking conditions around the port.",
        "spot_country": "Spain",
        "spot_city": "Gijon",
        "spot_street": "Playa de Poniente",
        "spot_street_number": "1",
        "latitude": 43.5432,
        "longitude": -5.6736,
    },
    {
        "spot_name": "Skatepark de Cimavilla",
        "sport_type": "skateboarding",
        "spot_description": "A city-centre skate session near the old quarter and the waterfront.",
        "spot_country": "Spain",
        "spot_city": "Gijon",
        "spot_street": "Cimavilla",
        "spot_street_number": "1",
        "latitude": 43.5458,
        "longitude": -5.6639,
    },
    {
        "spot_name": "Skatepark de Moreda",
        "sport_type": "skateboarding",
        "spot_description": "Open-air concrete spot in the Moreda area. Verify access and surface conditions locally.",
        "spot_country": "Spain",
        "spot_city": "Gijon",
        "spot_street": "Parque de Moreda",
        "spot_street_number": "1",
        "latitude": 43.5385,
        "longitude": -5.6960,
    },
    {
        "spot_name": "Parque Fluvial del Piles",
        "sport_type": "bmx",
        "spot_description": "A riverside route with open space for BMX lines and a quick warm-up near Viesques.",
        "spot_country": "Spain",
        "spot_city": "Gijon",
        "spot_street": "Parque Fluvial del Piles",
        "spot_street_number": "1",
        "latitude": 43.5238,
        "longitude": -5.6358,
    },
]
